#!/usr/bin/env python3
# @license
# Copyright 2026 Google LLC
# SPDX-License-Identifier: Apache-2.0

"""Export the a2g_models LLM registry to models.default.json.

This is an optional convenience tool — it regenerates models.default.json from
the Python a2g_models registry.  It is NOT required at runtime.

Usage (run from the a2g_models project root):
    cd ~/workspace/main/research/a2g_packages/src/a2g_models
    uv run --native-tls --env-file ~/.env \
      python ~/workspace/gemini-cli-fork/scripts/fork/export_llm_registry.py

Output:
    ~/workspace/gemini-cli-fork/models.default.json
"""

import json
import os

from a2g_models.registries.llm_registries import LLMRegistry

# Write to the repo root's models.default.json
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(os.path.dirname(SCRIPT_DIR))
OUTPUT_PATH = os.path.join(REPO_ROOT, "models.default.json")


def export_model(config) -> dict:
    """Convert a single LLMConfig to a JSON-serializable dict with camelCase keys."""
    entry = {
        "model": config.model,
        "url": config.url,
        "contextLength": config.context_length,
        "maxTokens": config.max_tokens,
        "corp": config.corp,
        "home": getattr(config, "home", False),
        "dev": getattr(config, "dev", False),
        "supportsResponsesApi": getattr(config, "supports_responses_api", False),
        "reasoningModel": getattr(config, "reasoning_model", False),
    }

    if config.model_alias:
        entry["modelAlias"] = config.model_alias

    if config.modality:
        entry["modality"] = config.modality

    if config.api_key_env:
        entry["apiKeyEnv"] = config.api_key_env

    if config.extra_body:
        entry["extraBody"] = config.extra_body

    # For defaultHeaders that depend on env vars at runtime,
    # store a marker so TypeScript can compute them lazily.
    if config.default_headers:
        if "x-dep-ticket" in config.default_headers:
            entry["defaultHeaders"] = "__corp_auth__"
        else:
            entry["defaultHeaders"] = config.default_headers

    return entry


def main():
    models = [export_model(config) for config in LLMRegistry._models.values()]

    output = {
        "_comment": "Auto-generated by scripts/fork/export_llm_registry.py. Do not edit manually.",
        "models": models,
    }

    with open(OUTPUT_PATH, "w") as f:
        json.dump(output, f, indent=2)

    print(f"Exported {len(models)} models to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
